name: Scripts jobs audio downloading

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  #workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/moorecollection
  IMAGE_TAG: latest
  PYTHONPATH: ${{ github.workspace }}

jobs:
  run-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Docker Image Name
        run: echo "Docker image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker Image
        run: docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Run Python Script Inside Docker
        run: docker run --rm \
              -v ${{ github.workspace }}:/app \
              -w /app \
              --env AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
              --env AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
              --env AWS_ENDPOINT_URL_S3=${{ secrets.AWS_ENDPOINT_URL_S3 }} \
              --env AWS_REGION=${{ secrets.AWS_REGION }} \
              ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} /bin/bash -c "
                python /app/scripts/job_download_audios.py"
